server:
  port: 8085

spring:
  application:
    name: service-map

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-map?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: 123456
    password: 123456


#自定义的key:value
amap:
  key: 855fdd30e0365567e41e840f2a05c967