server:
  port: 9000

spring:
  application:
    name: sse-driver-client-web
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


  mvc:
    view:
      prefix: /static/
      suffix: .jsp